### ISSUE TITLE
Automatically add milestones to issues when they are closed

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak-github-bot#5]
### Description

When a issue is closed with a linked PR the milestone should be automatically updated:

* If PR is sent to main branch the next major/minor milestone should be applied
* If PR is sent to a release branch the corresponding milestone should be applied
* If issue is closed without a linked PR the milestone should be cleared

### Motivation

Issues are frequently closed without the correct milestone set. This results in the issue not being included in the release notes, as well as making it harder to discover for what release a given issue was resolved. To make sure the correct milestone is always set this should be automated.

**Comment by stianst** [comment]
One challenge is I'm not quite sure how you see if an issue has a linked PR. I think it can only be done by going through the events for the issue :/

**Comment by ahus1** [comment]
With the issue labeler in place which adds release labels to an issue, this might no longer be needed. Suggesting to close this.
